# Generated by Django 4.2.14 on 2024-08-12 07:22

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_alter_profilemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])], verbose_name='image'),
        ),
    ]
